### ISSUE TITLE
Not supported call of $GLOBALS['TT']->setTSlogMessage()

### ISSUE THREAD

**Issue by dklimpel** [rupertgermann/tt_news#89] opened 2017-08-06 18:49 UTC
The use of $GLOBALS['TT']->setTSlogMessage() in class.tx_ttnews.php line 3897 is not supported anymore:
[TYPO3 Documentation](https://docs.typo3.org/typo3cms/extensions/core/8.7/singlehtml/Index.html#breaking-73504-make-timetracker-a-singleton)

Solution:
>\TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(\TYPO3\CMS\Core\TimeTracker\TimeTracker::class)->setTSlogMessage('Using alternative subpart marker for \'' . $subpartMarker . '\': ' . $altSPM, 1);

**Comment by rupertgermann** [comment] 2018-11-16 17:25
duplicate of https://github.com/rupertgermann/tt_news/issues/103
fixed

**Closed as completed by rupertgermann** 2018-11-16 17:25 UTC
