### ISSUE TITLE
Not compatible with TYPO3 v8 LTS (8.7)

### ISSUE THREAD

**Issue by Patta** [rupertgermann/tt_news#67] opened 2017-04-05 14:46 UTC
composer why-not typo3/cms:8.7.0

typo3-ter/tt-news                              7.6.3    requires          typo3/cms-core (>= 7.6.0, <= 7.6.99)

**Comment by derhecht** [comment] 2017-04-06 09:57
atm it is not official supported, thats why. may someone should use it in 8 and approve usage that we can drop this limitation. never the less, just create a PR to change it may to >= 8.7?

**Comment by sir-gawain** [comment] 2017-04-06 10:03
Currently it does not run in 8.7 out of the box.

**Comment by christianfutterlieb** [comment] 2017-04-06 12:08
I have a fresh install of tt_news on 8.7.0. I made following observations in a not-very-in-depth test:
* Backend module does not work (additionally an exception is thrown in "About Modules")
* TCA works more or less, needs some migrations
* Frontend plugin in LIST, LATEST and SINGLE seem to work (with only the basic static template included)

I'm not deeply familiar with all the options and features of tt_news. Anyway, we use it in lots of installations in my company and we'd like to help to keep it running. I'd go for TCA migrations stuff and bring up a pr later this afternoon.

**Comment by christianfutterlieb** [comment] 2017-04-06 18:37
Hey folks

Please checkout the changes in pr #74 . Tested on TYPO3 7.6.16 and 8.7.0.

Hope to find some time tomorrow to tackle the be module.

**Comment by sir-gawain** [comment] 2017-04-06 19:06
Not sure, if its a problem with 8.7 or the xml files, but i do not have German translations in the backend forms. Tried to use EXT:ew_llxml2xliff to convert the xml to xliff, but it also fails and generated empty language files.

**Comment by christianfutterlieb** [comment] 2017-04-06 20:26
@sir-gawain check out e9cfe5be1231afd9cccb885359a5043c92dfe4e2 from pr #74

**Comment by sir-gawain** [comment] 2017-04-07 07:29
Applied your branch and the labels are working again! Thx.

**Comment by christianfutterlieb** [comment] 2017-04-07 17:35
Hi folks

I did some work on the compatibility of the backend module, see #75. If there's somebody around here more familiar with the code, please approve. Or take the code as base for further work.
Thx & cheers!

ps: I split the two pr's apart on purpose, as #74 seems "easier" to me.

**Comment by Patta** [comment] 2017-04-10 09:20
i get this frontend exception with current master and pr 74 and 75:

> Call to undefined method TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer::IMAGE() 

Error thrown in file
...\htdocs\typo3_8\web\typo3conf\ext\tt_news\pi\class.tx_ttnews.php in line 2219.

maybe a composer misconfiguration? i added this to my composer.json to run tt_news:
`"autoload": {
        "classmap": [
            "web/typo3conf/ext/tt_news/pi",
            "web/typo3conf/ext/tt_news/mod1",
            "web/typo3conf/ext/tt_news/lib"
        ],
        "psr-4": {
          "WMDB\\TtNews\\": "web/typo3conf/ext/tt_news/Classes/",
          "WMDB\\TtNews\\Lib\\": "web/typo3conf/ext/tt_news/lib/"
        }
    },
`

thanks

**Comment by sir-gawain** [comment] 2017-04-10 09:42
No, IMAGE() was deprecated and has been removed from code. I pushed a fix for that.

**Comment by akerssies** [comment] 2017-04-10 13:03
Is there an expected release date for the v8 compatibility ?

**Comment by Patta** [comment] 2017-04-10 19:30
@sir-gawain Thanks!
@akerssies As typo3-ter release probably never, the extension owner seems to be very busy :)

**Comment by derhecht** [comment] 2017-04-20 10:00
I've now a working T3 8.7 setup with tt_news installed. Looking forward to include your work.

**Comment by derhecht** [comment] 2017-04-20 10:06
see https://forge.typo3.org/issues/79927

**Comment by derhecht** [comment] 2017-04-20 10:24
I would prefer to instand drop TYPO3 <= 8.7 support as it is hard enough to support just one version at all.

**Comment by christianfutterlieb** [comment] 2017-04-20 10:33
@derhecht imho 7.6 compatibility should remain as long as 7.6 it officially supported by TYPO3. At least it's an LTS version and will be around until end of 2018. I'd prefer to support 7.6.0-8.7.x

**Comment by derhecht** [comment] 2017-04-20 11:35
but those guys can stay at 7.6.3. no features will be added.

**Comment by christianfutterlieb** [comment] 2017-04-20 13:37
true. Anyway, the changes in the prs work on both 7.6 ans 8.7.

**Comment by christianfutterlieb** [comment] 2017-04-20 13:45
Besides, things like `getLocallangSplitLabelForExtLang()` (see e9cfe5be1231afd9cccb885359a5043c92dfe4e2), or `WMDB\TtNews\Utility\IconUtility` (364eb9d4ca89fd48edad4d43f89ef242b49f9acb) seem to be a little overkill, but could come in handy when it comes to upgrading tt_news for subsequent TYPO3 versions again ;-)

**Comment by derhecht** [comment] 2017-04-20 14:22
I'm working on a commit based on your TCA migrations PR but without the getLocallangSplitLabelForExtLang.

**Comment by derhecht** [comment] 2017-04-21 14:02
done so far, please create new issues on concrete TYPO3 8 problems

**Closed as completed by derhecht** 2017-04-21 14:02 UTC

**Comment by ProWebs** [comment] 2018-03-03 14:07
Got after activation this error:
Call to undefined method TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController::getStorageSiterootPids()

Error thrown in file
/var/www/html/htdocs/typo3conf/ext/tt_news/pi/class.tx_ttnews.php in line 3536.

**Comment by w010** [comment] 2018-03-03 15:48
For quick solution you can try set useStoragePid=0 (if your setup allows that)
It's used mainly for category tree. If you have one root and not many categories in various places, it may work ok with that setting.
The reason of that error is that it tries to find root page of current pagetree / page with the nearest setting "General record storage page", which doesn't exist in 8.x anymore, as well as that called TSFE method. It must be reworked to explicitly set this pid manually per root or global.

**Comment by ProWebs** [comment] 2018-03-05 15:16
Where exactly do you mind? Templates -> Setup? 
Smth. like: plugin.tt_news.useStoragePid = 0  ?

Now i get no output from tt_news on frontend. Everything around is rendering fine.

**Comment by rupertgermann** [comment] 2018-03-05 15:18
no, it's a global setting in the extension settings in Extensionmanager

**Comment by ProWebs** [comment] 2018-03-05 15:28
You mean here:  Configure Extension tt_news? Sorry but I can't see a setting called useStoragePid here.

**Comment by rupertgermann** [comment] 2018-03-05 15:34
yes. the label of the option is: Use "General record storage page"

**Comment by adrienjacob** [comment] 2018-03-06 07:52
Well, actually the parameter is no longer available (I guess since commit https://github.com/rupertgermann/tt_news/commit/a832ee3474566cce77b304854ccb26b79bf0f795#diff-8ee17d276215f3affcd87ac9221ab664) and it did create some issues for me when upgrading to Typo3 v8. 
Couldn't we set this param to 0 by default ?

**Comment by w010** [comment] 2018-03-06 11:44
On new installation problem cannot be reproduced. If you upgraded your installation, this setting might be written in your LocalConfiguration.php - you can edit tt_news serialized config there or remove the whole line and clean reconfigure ext from Extension Manager.
