### ISSUE TITLE
In TYPO3 8 LTS the field "endtime" is always set to an fixed value when saving a tt_news record

### ISSUE THREAD

**Issue by weberdigital** [rupertgermann/tt_news#100] opened 2018-03-08 12:01 UTC
When you try to set an `endtime` in a tt_news record, the value is always set to a fixed value while saving.

Unsetting the `endtime` works correctly.

Neither the `starttime` field of the tt_news nor the `starttime` and `endtime` fields of the tt_content table have these bugs.

**Comment by guppy42** [comment] 2018-03-13 14:13
It's not fixed, it is however wrong in tt_news/Configuration/TCA/tt_news.php locate the line :

'lower' => mktime(0, 0, 0, date('m') - 1, date('d'), date('Y'))

and comment it out, this "fixes" the issue. 

It seems that inputDateTime aren't being parsed correctly

**Comment by weberdigital** [comment] 2018-03-14 08:59
> It seems that inputDateTime aren't being parsed correctly

So, it's a bug in TYPO3 8?

**Comment by rupertgermann** [comment] 2018-03-14 09:20
it's not a bug it's a feature ;-)
since some time the complete TCA is parsed and then the result is stored as a serialized string. means: the mktime function is only executed once and then its result will be cached. If you open a new news record than the cached value is inserted to the editform. Depending on when the tca cache was created this value is wrong.
short (ugly) fix: clear the tca cache once a day. You can do this with the extension  coreapi which provides a scheduler job for this.
real fix: implement a FormdataProvider which inserts the correct date during form rendering (ext: news is doing this in this way)

**Comment by guppy42** [comment] 2018-03-14 10:19
@rupertgermann  then there are two seperate issues :)

1) "min" for end date being a fixed date 

2) local dates getting parsed wrong and replaced with the min value regardless of what is entered.

**Comment by rupertgermann** [comment] 2018-11-08 17:43
please use latest master where this issue should be fixed

**Closed as completed by rupertgermann** 2018-11-08 17:43 UTC
