### ISSUE TITLE
Fix for issue #31 breaks category selection for normal users

### ISSUE THREAD

**Issue by heisenbol** [rupertgermann/tt_news#40] opened 2017-02-12 10:58 UTC
I hit the problem described in issue #31 after upgrading to TYPO3 7.6 and updating tt_news to 7.6.3. I installed the current master of tt_news to try out the merged fix for this.

Now my normal backend users have no categories to choose from at all. Editing a news item has no categories to choose from.

Going to the list module, the users get to see correctly only the categories they have access to. But editing a news item has an empty category list.

**Comment by derhecht** [comment] 2017-02-14 14:51
Mmh, I cannot reproduce it atm. Could you please provide more setting details? Which way of excluding categories do you use (tree or TypoScript)?
I understand right that you are able to create new news without problems but edit existing ones fails regarding category selection?

**Comment by heisenbol** [comment] 2017-02-14 15:17
thanks for the feedback. 
I use the BE group of my users to allow access to specific categories. My categories are spread throughout the page tree. 

I did not try to create new news, but I assume that even for new news I will have an empty category list. So I won't be able to assign categories to my news.

Another comment: in my initial report, "Going to the list module" should have been "Going to the News module". In the news module, I see the correct categories, but editing a news item has an empty category list.

In any case, I will reinstall the master version and will try out a cleaner setup. I should get back to you till the end of the week.

**Comment by heisenbol** [comment] 2017-02-18 12:05
Hi again.

I came up with the following test cases that stop working. Both worked with TYPO3 6.2. Under 7.6 and the latest published tt_news, they continue to work, but display all the available news categories and not only the ones the user has access to (which should have been fixed with issue #31 ):

A BE user has a BE group that is restricted to specific news categories. The restriction is applied through a selection in the BE group tab "extended". In the following hierarchy, the BE Group has access to UserCat1

SuperCat
|---UserCat1
|------UserSubcat1

The news categories UserCat1 and UserSubcat1 are stored in a Folder NewsCatFolder.

What I would expect is that regardless of the location of SuperCat or the access permissions to SuperCat, the user can assign the categories UserCat1 and/or UserSubcat1 to a news item.

1) Case 1 - The parent category SuperCat is stored in another folder.
Editing a news item displays an empty news category list.
Even if the BE Group has additional access to SuperCat, the category list remains empty.
The News Module always does show UserCat1 and UserSubcat1

2) Case 2 - The parent category SuperCat is stored in the same folder NewsCatFolder as the other categories
Editing a news item displays an empty news category list.
If the BE Group gets additional access to SuperCat, the category list is displayed correctly.
The News Module always does show UserCat1 and UserSubcat1

**Comment by derhecht** [comment] 2017-03-14 11:04
tried useStoragePid = 0?

as far as I understand the only problem here is that list is empty when SuperCat is in another folder.

**Comment by heisenbol** [comment] 2017-03-16 13:24
I'll try this in the next days and will get back here.

Even when the SuperCat is in the same folder, the list remains empty if the loged in user does not have access to the SuperCat (see Case 2).

What is curious is that the News module does display the category list correctly regardless of the location of SuperCat or it's permissions. I'd say that the category list of the news module should be the same as the category list in the edit news screen, which is not the case right now.

**Comment by heisenbol** [comment] 2017-03-18 12:37
I tried setting useStoragePid = 0 with the current master. The result was the same. Still an empty category list.

**Comment by derhecht** [comment] 2017-04-03 12:22
Do you use any other extension which may revers/extend/use tt_news?

**Comment by derhecht** [comment] 2017-04-03 12:30
Is this may linked with #58 ?

**Comment by heisenbol** [comment] 2017-04-03 12:42
> Do you use any other extension which may revers/extend/use tt_news?

not really. I do have a custom extension, that just adds records to tt_news, but otherwise does not interfere with it's TCA or anything else

> Is this may linked with #58 ?

hmmm... I would say that #58 is a duplicate of #31, which you fixed and then my issue was caused

**Comment by derhecht** [comment] 2017-04-03 13:04
are you able to figure out which part of the two #31 commits is responsible for this issue here?

**Comment by heisenbol** [comment] 2017-04-03 13:15
I can try, but I'm not optimistic that I will figure it out. I'll get back to this, probably on the weekend

**Comment by heisenbol** [comment] 2017-04-08 14:33
I've looked into the commits, and although I couldn't find the exact issue, i got more insight into the problem and hope I can help to pinpoint the root cause of this issue.

I looked into WMDB\TtNews\Tree\TableConfiguration\NewsDatabaseTreeDataProvider which seems to create all this trouble.

In my case, I saw that in the final loop, where each child is checked for whether it is within the allowedItems, non of the childs were, and thus no nodes were created. The returned storage is empty and the tree in the news edit screen empty.

The allowedItems are got from tx_ttnews_div::getAllowedTreeIDs and are correct.
The checked children are all 1st level categories (don't understand why)

Now here is the thing: My category tree is of the form
```
Level1
|----- SubCatL2
        |----- SubCatL3
```

My user has access to SubCatL3 and below.
If I move SubCatL3 up one level (to level 2), the tree works! 

So I understand that the this class can't cope with access to categories that have no direct connection to the 1st level categories. This used to work in the past.

Unfortunately for me, I can't really move my deep categories up. It wouldn't work for my installation.

I don't know if I make sense with my description. I will be happy to clarify things up or make more tests.

**Comment by heisenbol** [comment] 2017-05-12 08:07
Hi again. I wanted to ask if there is any new development in this issue. If you need me to do more tests, please feel free to contact me

**Comment by sterborg** [comment] 2017-09-12 09:54
Hello, I have the same problem and would appreciate a solution or workaround.

**Comment by rupertgermann** [comment] 2018-11-08 17:46
please use latest master where this issue should be fixed

**Closed as completed by rupertgermann** 2018-11-08 17:46 UTC
